---
- name: Install WireGuard srv
  hosts: your_host
  become: yes

  tasks:
    - name: Update server
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install WireGuard
      ansible.builtin.apt:
        name: wireguard
        state: present

    - name: Generate key
      ansible.builtin.shell:
        cmd: "wg genkey | tee /etc/wireguard/privatekey | wg pubkey | tee /etc/wireguard/publickey"
        creates: /etc/wireguard/privatekey

    - name: Set permissions for private key
      ansible.builtin.file:
        path: /etc/wireguard/privatekey
        mode: '0600'
