---
- name: Install Jenkins
  hosts: follower
  become: true

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install fontconfig and OpenJDK 17 JRE
      ansible.builtin.apt:
        name:
          - ca-certificates
          - wget
          - gnupg
          - lsb-release
          - openjdk-21-jre
          - maven
        state: present

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download and install Docker GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
          sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Create Docker repository configuration
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture) \
          signed-by=/etc/apt/keyrings/docker.gpg] \
          https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list

    - name: Update package cache for Docker repository
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Create Jenkins group
      ansible.builtin.group:
        name: jenkins
        state: present

    - name: Create Jenkins user
      ansible.builtin.user:
        name: jenkins
        group: jenkins
        home: /home/jenkins
        shell: /bin/bash
        state: present

    - name: Add Jenkins to the docker group
      ansible.builtin.user:
        name: jenkins
        groups: docker
        append: yes

    - name: Add Jenkins to the sudo group
      ansible.builtin.user:
        name: jenkins
        groups: sudo
        append: yes
