---
- name: Install Jenkins
  hosts: follower
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install fontconfig and OpenJDK 17 JRE
      apt:
        name:
          - ca-certificates
          - wget
          - gnupg
          - lsb-release
          - openjdk-21-jre
          - maven
        state: present

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory

    - name: Download and install Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Create Docker repository configuration
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update package cache for Docker repository
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install Docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Create Jenkins group
      group:
        name: jenkins
        state: present

    - name: Create Jenkins user
      user:
        name: jenkins
        group: jenkins
        home: /home/jenkins
        shell: /bin/bash
        state: present

    - name: Add Jenkins to the docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Add Jenkins to the sudo group
      user:
        name: jenkins
        groups: sudo
        append: yes